/** Deckmaker-exported cards not yet in deck_data.js (images omitted — resolved via assets/cards/{id}.png). */
export default [
  {
    id: "card_1782315551233",
    name: "第６サラマンダー混成支援大隊",
    type: "ユニット",
    world: "ユニフォール",
    attack: 1,
    defense: 3,
    description: "出撃時：２枚ドローする",
    flavorText: "サラマンダーはお手伝いが大好き！...機関銃も握れる！",
    tags: ["ルディワ公国", "歩兵", "戦車", "機械", "魔物", "車両"],
    costs: {
      play: { nature: 2, human: 2, fuel: 0, gold: 0, mineral: 0, electric: 0, magic: 0 },
      act: { nature: 1, human: 0, fuel: 0, gold: 0, mineral: 0, electric: 0, magic: 0 },
      choice: [],
      choiceAct: [],
    },
    generates: { mineral: 0, magic: 0, electric: 0, nature: 0, fuel: 0, gold: 0, human: 0 },
    limit: 4,
    roles: [],
    tactSubType: null,
    rarity: "通常",
    imageUrl: "assets/cards/card_1782315551233.jpeg",
  },
  {
    id: "card_1782307790847",
    name: "北東軍第33師団砲中隊",
    type: "ユニット",
    world: "ユニフォール",
    attack: 2,
    defense: 2,
    description: "[衝撃][曲射②]",
    flavorText: "「本格的な砲撃支援に比べたら貧相かもしれないが、\n衝撃と畏怖を叩き込むには必要不可欠だ。」",
    tags: ["アトラス北東軍", "純人間", "獣", "龍", "砲"],
    costs: {
      play: { human: 1, mineral: 2, fuel: 0, gold: 0, nature: 0, electric: 0, magic: 0 },
      act: { mineral: 2, human: 0, fuel: 0, gold: 0, nature: 0, electric: 0, magic: 0 },
      choice: [],
      choiceAct: [],
    },
    generates: { mineral: 0, magic: 0, electric: 0, nature: 0, fuel: 0, gold: 0, human: 0 },
    limit: 4,
    roles: [],
    tactSubType: null,
    rarity: "通常",
    imageUrl: "assets/cards/card_1782307790847.jpeg",
  },
  {
    id: "card_1782303856785",
    name: "第8装甲騎兵大隊",
    type: "ユニット",
    world: "ユニフォール",
    attack: 4,
    defense: 6,
    description: "[貫通①][装甲②][機動][警戒]",
    flavorText: "我ら、騎兵の誇り。第8、雪原より砂漠に至るまで、誰にも劣らぬ精鋭なり。",
    tags: ["グラダナ連邦共和国", "純人間", "獣", "龍", "歩兵", "車両"],
    costs: {
      play: { fuel: 2, gold: 1, human: 3, nature: 0, mineral: 0, electric: 0, magic: 0 },
      act: { fuel: 1, gold: 1, nature: 1, human: 0, mineral: 0, electric: 0, magic: 0 },
      choice: [],
      choiceAct: [],
    },
    generates: { nature: 0, magic: 0, electric: 0, mineral: 0, fuel: 0, human: 0, gold: 0 },
    limit: 4,
    roles: [],
    tactSubType: null,
    rarity: "通常",
    imageUrl: "assets/cards/card_1782303856785.jpeg",
  },
  {
    id: "card_1782287759412",
    name: "DTO前線指揮所",
    type: "コア",
    world: "ユニフォール",
    life: 20,
    defense: 20,
    handLimit: 7,
    drawPerTurn: 1,
    initialHand: 6,
    limit: 4,
    description:
      "[アトラス北東軍][グラダナ連邦共和国][ルディワ公国]タグのプレイコスト5以下のカードを20枚以上入れていない場合、このカードは使用できない。\n[アトラス北東軍][グラダナ連邦共和国][ルディワ公国]タグのユニット全員がATK+①の修正を得る",
    flavorText: "締約勢力は、共同の安全を回復および維持するため、\n必要と認める行動を直ちに実施する。",
    tags: ["グラダナ連邦共和国", "アトラス北東軍", "ルディワ公国"],
    initialResources: { mineral: 1, gold: 4, human: 2, nature: 0, fuel: 0, electric: 0, magic: 0 },
    defeatCondition: "このカードが破壊される。",
    costs: { play: {}, act: {}, choice: [], choiceAct: [] },
    generates: {},
    roles: [],
    tactSubType: null,
    rarity: "通常",
    imageUrl: "assets/cards/card_1782287759412.jpeg",
  },
  {
    id: "card_1782311181226",
    name: "壊滅怪異",
    type: "ユニット",
    world: "阿依の国のジャータカ",
    attack: 0,
    defense: 1,
    description: "[機動][自爆⑩]",
    flavorText: "「あと一度の攻勢で我々は勝利する」その言葉は三年前にも聞いた。",
    tags: ["機械", "ロボット", "怪異"],
    costs: {
      play: { magic: 1, mineral: 1, fuel: 0, gold: 0, nature: 0, human: 0, electric: 0 },
      act: { electric: 0, magic: 0, mineral: 0, nature: 0, fuel: 0, gold: 0, human: 0 },
      choice: [],
      choiceAct: [],
    },
    generates: { fuel: 0, human: 0, gold: 0, nature: 0, magic: 0, mineral: 0, electric: 0 },
    limit: 4,
    roles: [],
    tactSubType: null,
    rarity: "通常",
    imageUrl: "assets/cards/card_1782311181226.jpeg",
  },
  {
    id: "card_1782237267608",
    name: "北東軍第27迫撃砲分隊",
    type: "ユニット",
    world: "ユニフォール",
    attack: 1,
    defense: 1,
    description: "[衝撃][連撃①][曲射②]\n「歩兵」タグを持っているユニットに対し与攻撃時：ATK+①の修正を得る。",
    flavorText: "砲兵が戦場の女神だとしたら迫撃砲兵は戦場の天使なのだろうか？\n少なくとも、相手はそうは思っていないだろう。",
    tags: ["アトラス北東軍", "純人間", "獣", "龍", "歩兵", "砲"],
    costs: {
      play: { human: 1, mineral: 1, gold: 1, fuel: 0, nature: 0, electric: 0, magic: 0 },
      act: { nature: 1, human: 0, fuel: 0, gold: 0, mineral: 0, electric: 0, magic: 0 },
      choice: [],
      choiceAct: [],
    },
    generates: { mineral: 0, magic: 0, electric: 0, nature: 0, fuel: 0, gold: 0, human: 0 },
    limit: 4,
    roles: [],
    tactSubType: null,
    rarity: "通常",
    imageUrl: "assets/cards/card_1782237267608.jpeg",
  },
  {
    id: "card_1782308723608",
    name: "特別計画",
    type: "タクト",
    world: "ニュートラル",
    description: "コスト18以上のカードを2枚、手札に加える",
    flavorText: "「我々の計画は必ず世界を席巻させる。\nその為には諸君らの弛まぬ努力が＿」",
    tags: ["政策", "計画"],
    costs: {
      play: { gold: 1, human: 0, magic: 0, electric: 0, nature: 0, fuel: 0, mineral: 0 },
      act: {},
      choice: [],
      choiceAct: [],
    },
    generates: { gold: 0, mineral: 0, nature: 0, fuel: 0, electric: 0, magic: 0, human: 0 },
    limit: 4,
    roles: [],
    tactSubType: "通常",
    rarity: "通常",
    imageUrl: "assets/cards/card_1782308723608.jpeg",
  },
];
