/** Deckmaker-exported cards not yet in deck_data.js (images omitted — resolved via assets/cards/{id}.png). */
export default [
  {
    id: "card_1782315551233",
    name: "第６サラマンダー混成支援大隊",
    type: "ユニット",
    world: "ユニフォール",
    attack: 1,
    defense: 3,
    description: "出撃時：２枚ドローする",
    flavorText: "サラマンダーはお手伝いが大好き！...機関銃も握れる！",
    tags: ["ルディワ公国", "歩兵", "戦車", "機械", "魔物", "車両"],
    costs: {
      play: { nature: 2, human: 2, fuel: 0, gold: 0, mineral: 0, electric: 0, magic: 0 },
      act: { nature: 1, human: 0, fuel: 0, gold: 0, mineral: 0, electric: 0, magic: 0 },
      choice: [],
      choiceAct: [],
    },
    generates: { mineral: 0, magic: 0, electric: 0, nature: 0, fuel: 0, gold: 0, human: 0 },
    limit: 4,
    roles: [],
    tactSubType: null,
    rarity: "通常",
    imageUrl: "assets/cards/card_1782315551233.jpeg",
  },
  {
    id: "card_1782307790847",
    name: "北東軍第33師団砲中隊",
    type: "ユニット",
    world: "ユニフォール",
    attack: 2,
    defense: 2,
    description:
      "[衝撃]　[曲射②]\n[歩兵]タグのユニットに対し時与攻撃時：ATK+１の修正を得る\n隣接するユニットのうち2つが[アトラス北東軍]のタグのユニットの時：ATK+１の修正を得る、HP+１の修正を得る",
    flavorText: "「本格的な砲撃支援に比べたら貧相かもしれないが、\n衝撃と畏怖を叩き込むには必要不可欠だ。」",
    tags: ["アトラス北東軍", "純人間", "獣", "龍", "砲"],
    costs: {
      play: { human: 1, mineral: 2, fuel: 0, gold: 0, nature: 0, electric: 0, magic: 0 },
      act: { mineral: 2, human: 0, fuel: 0, gold: 0, nature: 0, electric: 0, magic: 0 },
      choice: [],
      choiceAct: [],
    },
    generates: { mineral: 0, magic: 0, electric: 0, nature: 0, fuel: 0, gold: 0, human: 0 },
    limit: 4,
    roles: [],
    tactSubType: null,
    rarity: "通常",
    imageUrl: "assets/cards/card_1782307790847.jpeg",
  },
  {
    id: "card_1782303856785",
    name: "第8装甲騎兵大隊",
    type: "ユニット",
    world: "ユニフォール",
    attack: 4,
    defense: 6,
    description: "[貫通①][装甲②][機動][警戒]",
    flavorText: "我ら、騎兵の誇り。第8、雪原より砂漠に至るまで、誰にも劣らぬ精鋭なり。",
    tags: ["グラダナ連邦共和国", "純人間", "獣", "龍", "歩兵", "車両"],
    costs: {
      play: { fuel: 2, gold: 1, human: 3, nature: 0, mineral: 0, electric: 0, magic: 0 },
      act: { fuel: 1, gold: 1, nature: 1, human: 0, mineral: 0, electric: 0, magic: 0 },
      choice: [],
      choiceAct: [],
    },
    generates: { nature: 0, magic: 0, electric: 0, mineral: 0, fuel: 0, human: 0, gold: 0 },
    limit: 4,
    roles: [],
    tactSubType: null,
    rarity: "通常",
    imageUrl: "assets/cards/card_1782303856785.jpeg",
  },
  {
    id: "card_1782287759412",
    name: "DTO前線指揮所",
    type: "コア",
    world: "ユニフォール",
    life: 20,
    defense: 20,
    handLimit: 7,
    drawPerTurn: 1,
    initialHand: 6,
    limit: 4,
    description:
      "[アトラス北東軍][グラダナ連邦共和国][ルディワ公国]タグのプレイコスト5以下のカードを20枚以上入れていない場合、このカードは使用できない。\n[アトラス北東軍][グラダナ連邦共和国][ルディワ公国]タグのユニット全員がATK+①の修正を得る",
    flavorText: "締約勢力は、共同の安全を回復および維持するため、\n必要と認める行動を直ちに実施する。",
    tags: ["グラダナ連邦共和国", "アトラス北東軍", "ルディワ公国"],
    initialResources: { mineral: 1, gold: 4, human: 2, nature: 0, fuel: 0, electric: 0, magic: 0 },
    defeatCondition: "このカードが破壊される。",
    costs: { play: {}, act: {}, choice: [], choiceAct: [] },
    generates: {},
    roles: [],
    tactSubType: null,
    rarity: "通常",
    imageUrl: "assets/cards/card_1782287759412.jpeg",
  },
  {
    id: "card_1782520000000",
    name: "北東軍総司令部",
    type: "コア",
    world: "ユニフォール",
    life: 16,
    handLimit: 7,
    drawPerTurn: 1,
    initialHand: 5,
    limit: 4,
    description:
      "[装甲③]\nターン開始時：人を得る。\n「北東軍最高司令官」ユニットがデッキに含まれていない場合、このカードは使用できない。",
    flavorText:
      "この若き国家は抑えきれぬ軍拡の熱意と野心に包まれている。その矛先をいつまで国外に向けられるか。",
    tags: ["アトラス北東軍"],
    initialResources: { gold: 5, human: 2, nature: 0, mineral: 0, fuel: 0, electric: 0, magic: 0 },
    generates: {},
    defeatCondition: "このカードが破壊される。「北東軍最高司令官」ユニットが破壊される。",
    costs: { play: {}, act: {}, choice: [], choiceAct: [] },
    roles: [],
    tactSubType: null,
    rarity: "通常",
    imageUrl: "assets/cards/card_1782520000000.jpeg",
  },
  {
    id: "card_1782311181226",
    name: "壊滅怪異",
    type: "ユニット",
    world: "阿依の国のジャータカ",
    attack: 0,
    defense: 1,
    description: "[機動][自爆⑩]",
    flavorText: "「あと一度の攻勢で我々は勝利する」その言葉は三年前にも聞いた。",
    tags: ["機械", "ロボット", "怪異"],
    costs: {
      play: { magic: 1, mineral: 1, fuel: 0, gold: 0, nature: 0, human: 0, electric: 0 },
      act: { electric: 0, magic: 0, mineral: 0, nature: 0, fuel: 0, gold: 0, human: 0 },
      choice: [],
      choiceAct: [],
    },
    generates: { fuel: 0, human: 0, gold: 0, nature: 0, magic: 0, mineral: 0, electric: 0 },
    limit: 4,
    roles: [],
    tactSubType: null,
    rarity: "通常",
    imageUrl: "assets/cards/card_1782311181226.jpeg",
  },
  {
    id: "card_1782237267608",
    name: "北東軍第27迫撃砲分隊",
    type: "ユニット",
    world: "ユニフォール",
    attack: 1,
    defense: 1,
    description: "[衝撃][連撃①][曲射②]\n「歩兵」タグを持っているユニットに対し与攻撃時：ATK+①の修正を得る。",
    flavorText: "砲兵が戦場の女神だとしたら迫撃砲兵は戦場の天使なのだろうか？\n少なくとも、相手はそうは思っていないだろう。",
    tags: ["アトラス北東軍", "純人間", "獣", "龍", "歩兵", "砲"],
    costs: {
      play: { human: 1, mineral: 1, gold: 1, fuel: 0, nature: 0, electric: 0, magic: 0 },
      act: { nature: 1, human: 0, fuel: 0, gold: 0, mineral: 0, electric: 0, magic: 0 },
      choice: [],
      choiceAct: [],
    },
    generates: { mineral: 0, magic: 0, electric: 0, nature: 0, fuel: 0, gold: 0, human: 0 },
    limit: 4,
    roles: [],
    tactSubType: null,
    rarity: "通常",
    imageUrl: "assets/cards/card_1782237267608.jpeg",
  },
  {
    id: "card_1782308723608",
    name: "特別計画",
    type: "タクト",
    world: "ニュートラル",
    description: "コスト18以上のカードを2枚、手札に加える",
    flavorText: "「我々の計画は必ず世界を席巻させる。\nその為には諸君らの弛まぬ努力が＿」",
    tags: ["政策", "計画"],
    costs: {
      play: { gold: 1, human: 0, magic: 0, electric: 0, nature: 0, fuel: 0, mineral: 0 },
      act: {},
      choice: [],
      choiceAct: [],
    },
    generates: { gold: 0, mineral: 0, nature: 0, fuel: 0, electric: 0, magic: 0, human: 0 },
    limit: 4,
    roles: [],
    tactSubType: "通常",
    rarity: "通常",
    imageUrl: "assets/cards/card_1782308723608.jpeg",
  },
  {
    id: "card_1782225519182",
    name: "北東軍最高司令官",
    type: "ユニット",
    world: "ユニフォール",
    attack: 10,
    defense: 20,
    description:
      "[装甲⑩]　[貫通⑤]　[連撃①]　[神話]　[警戒]　[衝撃]　[機動]　[効果保護①]与ダメージ時：鉱④を得る、自④を得る\n非ダメージ時、自②を支払う：HP⑤の修正を得る\n「北東軍総司令部」がコアカードの時：ATK+⑤の修正を得る\nフィールド上に「アトラス北東軍」タグのユニットが存在する時：このユニットを除く対象ユニット全員がATK+③の修正を得る\nこのユニットは「アトラス北東軍」タグのユニットからのダメージを受けない。",
    flavorText:
      "「前線に赴くのは久々だな…この砲声と焦げ臭さも、将軍達の無謀な戦争計画を聞かされるよりはマシだな。」",
    tags: ["アトラス北東軍", "歩兵", "神話"],
    costs: {
      play: { human: 1, gold: 6, nature: 0, mineral: 6, fuel: 6, electric: 0, magic: 0 },
      act: { nature: 4, mineral: 4, gold: 0, human: 0, fuel: 0, electric: 0, magic: 0 },
      choice: [],
      choiceAct: [],
    },
    generates: { nature: 0, mineral: 0, gold: 0, human: 0, fuel: 0, electric: 0, magic: 0 },
    limit: 4,
    roles: [],
    tactSubType: null,
    rarity: "神話",
    imageUrl: "assets/cards/card_1782225519182.jpeg",
  },
  {
    id: "card_1782330659181",
    name: "ÜSPz.76V Aust. A",
    type: "ユニット",
    world: "ユニフォール",
    attack: 6,
    defense: 20,
    description:
      "[装甲⑧][貫通⑥][衝撃][機動][連撃①][曲射①]\n鉱6を支払う：ATK+④を得る",
    flavorText:
      "軍事費の無駄だと最高司令官に一蹴されたこの超重戦車は、技術将校達による数ヶ月にも及ぶ拷問とも思える“説得”によって製造許可が降りた。",
    tags: ["アトラス北東軍", "機械", "車両", "戦車"],
    costs: {
      play: { mineral: 15, fuel: 10, gold: 10, human: 2, nature: 0, electric: 0, magic: 0 },
      act: { gold: 5, fuel: 5, human: 0, nature: 0, mineral: 0, electric: 0, magic: 0 },
      choice: [],
      choiceAct: [],
    },
    generates: { gold: 0, mineral: 0, nature: 0, fuel: 0, electric: 0, magic: 0, human: 0 },
    limit: 4,
    roles: [],
    tactSubType: null,
    rarity: "通常",
    imageUrl: "assets/cards/card_1782330659181.jpeg",
  },
  {
    id: "card_1782361783127",
    name: "GNS Sovereign",
    type: "タクト",
    world: "ユニフォール",
    description: "すべての相手ユニットを破壊する",
    flavorText: "「自由なる海と、自由なる人民に、我らは奉仕する。」",
    tags: ["グラダナ連邦共和国", "命令"],
    costs: {
      play: { fuel: 8, gold: 8, mineral: 8, human: 8, electric: 0, magic: 0, nature: 0 },
      act: {},
      choice: [],
      choiceAct: [],
    },
    generates: { gold: 0, human: 0, nature: 0, mineral: 0, fuel: 0, electric: 0, magic: 0 },
    limit: 4,
    roles: [],
    tactSubType: "通常",
    rarity: "通常",
    imageUrl: "assets/cards/card_1782361783127.jpeg",
  },
  {
    id: "card_1782510000000",
    name: "第122戦車大隊",
    type: "ユニット",
    world: "ユニフォール",
    attack: 4,
    defense: 8,
    description: "[装甲④][貫通③][衝撃][機動][曲射①]",
    flavorText: "\"我ら鋼鉄の騎兵、連邦の槍と盾\"",
    tags: ["グラダナ連邦共和国", "機械", "車両", "戦車"],
    costs: {
      play: { gold: 4, human: 2, nature: 0, mineral: 3, fuel: 3, electric: 0, magic: 0 },
      act: { fuel: 3, mineral: 1, gold: 2, human: 0, nature: 0, electric: 0, magic: 0 },
      choice: [],
      choiceAct: [],
    },
    generates: { gold: 0, human: 0, nature: 0, mineral: 0, fuel: 0, electric: 0, magic: 0 },
    limit: 4,
    roles: [],
    tactSubType: null,
    rarity: "通常",
    imageUrl: "assets/cards/card_1782510000000.jpeg",
  },
  {
    id: "card_1755670973607",
    name: "王城ノーベルグ",
    type: "コア",
    world: "ヘルメネアの大地",
    defense: 20,
    description: "毎ターン：人②と金②を得る",
    initialResources: {
      human: 0,
      nature: 0,
      mineral: 0,
      gold: 8,
      electric: 0,
      fuel: 0,
      magic: 1,
    },
    generates: {
      human: 2,
      gold: 2,
      nature: 0,
      mineral: 0,
      fuel: 0,
      electric: 0,
      magic: 0,
    },
    tags: ["リ･サンティウ連合王国"],
    rarity: "通常",
  },
  {
    id: "card_1782225814944",
    name: "石油コンビナート",
    type: "ストラクト",
    world: "ユニフォール",
    description: "レストする：燃④を得る",
    generates: {
      fuel: 4,
      electric: 0,
      human: 0,
      mineral: 0,
      nature: 0,
      magic: 0,
      gold: 0,
    },
    costs: {
      play: { human: 1, nature: 0, mineral: 1, electric: 0, fuel: 0, magic: 0, gold: 1 },
      act: {},
      choice: [],
      choiceAct: [],
    },
    tags: ["産業", "工場", "科学"],
    rarity: "通常",
  },
  {
    id: "card_1782600000000",
    name: "戦時国債",
    type: "タクト",
    world: "ユニフォール",
    description:
      "自分のターンの始め金③を支払うことで墓地のこのカードを手札に加えてもよい。\n自分のコアカードに期限カウンター②と国債カウンター⑩をのせ、金⑥を得る。\n期限カウンター：自分のターンの終わりに①減らす。\n国債カウンター：期限カウンターが⓪ならカウンターの値を⓪にして金をその分だけ減らし、不足分はLPで支払う。",
    flavorText:
      "戦費は帳簿の数字ではなく、国民の血と汗で支払われる。だが戦が終われば、借金は必ず返さねばならない。",
    tags: ["経済", "財政", "戦争"],
    costs: {
      play: { gold: 0, human: 0, nature: 0, mineral: 0, fuel: 0, electric: 0, magic: 0 },
      act: {},
      choice: [],
      choiceAct: [],
    },
    generates: { gold: 0, human: 0, nature: 0, mineral: 0, fuel: 0, electric: 0, magic: 0 },
    limit: 4,
    roles: [],
    tactSubType: "通常",
    rarity: "通常",
    imageUrl: "assets/cards/card_1782600000000.jpeg",
  },
  {
    id: "card_1782610000000",
    name: "金準備を押収",
    type: "タクト",
    world: "ユニフォール",
    description:
      "永続タクト\n敵ユニットを撃破時：自分のコアカードに期限カウンターを+1し、金+1を得る。",
    flavorText:
      "前線で倒れた敵の懐から、戦費の足しにする。金庫の鍵は、勝者が握る。",
    tags: ["経済", "戦争", "占領"],
    costs: {
      play: { gold: 1, human: 1, nature: 0, mineral: 0, fuel: 0, electric: 0, magic: 0 },
      act: {},
      choice: [],
      choiceAct: [],
    },
    generates: { gold: 0, human: 0, nature: 0, mineral: 0, fuel: 0, electric: 0, magic: 0 },
    limit: 4,
    roles: [],
    tactSubType: "通常",
    rarity: "通常",
    imageUrl: "assets/cards/card_1782610000000.jpeg",
  },
  {
    id: "card_1782463436621",
    name: "露出管理",
    type: "タクト",
    world: "ニュートラル",
    description:
      "[永続]\nこのカードをレストして、自身の【機動】能力を持つレストしているユニットを1体まで選ぶ\nそのユニットを後退、右後退、左後退のいずれかをさせてもよい。\nそのユニットには煙幕カウンターを2載せる。\n\n煙幕カウンター：\n自分のターンの始めに1つ除去する\nこのカウンターがある限り、このユニットは[曲射]の能力を無視する。",
    flavorText: "重要な戦力こそ、敵の砲火を避けるべきだ。",
    tags: ["戦術.永続"],
    costs: {
      play: { fuel: 3, human: 0, nature: 0, mineral: 0, gold: 0, electric: 0, magic: 0 },
      act: {},
      choice: [],
      choiceAct: [],
    },
    generates: { gold: 0, human: 0, nature: 0, mineral: 0, fuel: 0, electric: 0, magic: 0 },
    limit: 4,
    roles: ["移動"],
    tactSubType: "通常",
    rarity: "通常",
    imageUrl: "assets/cards/card_1782463436621.jpeg",
  },
  {
    id: "card_1782464860185",
    name: "月下造山帯",
    type: "ストラクト",
    world: "ユニフォール",
    description: "人①燃①を支払いレストし、\n1枚ドローする、魔②を得る",
    flavorText: "致命的な点を除けば、最高の地域だ",
    tags: ["産業", "鉱山"],
    costs: {
      play: { gold: 3, human: 3, magic: 1, nature: 0, mineral: 0, fuel: 0, electric: 0 },
      act: {},
      choice: [],
      choiceAct: [],
    },
    generates: { gold: 0, human: 0, nature: 0, mineral: 0, fuel: 0, electric: 0, magic: 2 },
    limit: 4,
    roles: [],
    rarity: "通常",
    imageUrl: "assets/cards/card_1782464860185.jpeg",
  },
  {
    id: "card_1782462481137",
    name: "展開命令",
    type: "タクト",
    world: "ユニフォール",
    description: "[アトラス北東軍]タグのカードを4枚デッキから手札に加える",
    flavorText: "前線へ、一斉展開。",
    tags: ["アトラス北東軍", "命令"],
    costs: {
      play: { gold: 5, human: 0, nature: 0, mineral: 2, fuel: 2, electric: 0, magic: 0 },
      act: {},
      choice: [],
      choiceAct: [],
    },
    generates: { gold: 0, human: 0, nature: 0, mineral: 0, fuel: 0, electric: 0, magic: 0 },
    limit: 4,
    roles: [],
    tactSubType: "通常",
    rarity: "通常",
    imageUrl: "assets/cards/card_1782462481137.jpeg",
  },
  {
    id: "card_1782419351598",
    name: "北東軍に栄光あれ！",
    type: "タクト",
    world: "ユニフォール",
    description:
      "フィールド上に[アトラス北東軍]タグのユニットが存在する時：相手側のユニットを除く対象ユニット全員が[装甲⑤]を得る、HP+⑤の修正を得る、ATK+⑤の修正を得る",
    flavorText: "栄光は、前線に立つ者のものだ。",
    tags: ["アトラス北東軍", "戦術.永続"],
    costs: {
      play: { gold: 15, human: 0, nature: 5, mineral: 5, fuel: 5, electric: 0, magic: 0 },
      act: {},
      choice: [],
      choiceAct: [],
    },
    generates: { gold: 0, human: 0, nature: 0, mineral: 0, fuel: 0, electric: 0, magic: 0 },
    limit: 4,
    roles: [],
    tactSubType: "永続",
    rarity: "通常",
    imageUrl: "assets/cards/card_1782419351598.jpeg",
  },
  {
    id: "card_1782236231218",
    name: "北東軍第11対戦車歩兵中隊",
    type: "ユニット",
    world: "ユニフォール",
    attack: 1,
    defense: 4,
    description:
      "[貫通③][警戒]\n[装甲]効果を持っているユニットに対し与攻撃時：ATK+2の修正を得る\n隣接するユニットのうち2つが[アトラス北東軍]のタグのユニットの時：ATK+１の修正を得る、HP+１の修正を得る",
    tags: ["アトラス北東軍", "純人間", "歩兵"],
    costs: {
      play: { human: 2, gold: 1, mineral: 1, nature: 0, fuel: 0, electric: 0, magic: 0 },
      act: {},
      choice: [],
      choiceAct: [],
    },
    generates: { gold: 0, human: 0, nature: 0, mineral: 0, fuel: 0, electric: 0, magic: 0 },
    limit: 4,
    roles: [],
    rarity: "通常",
    imageUrl: "assets/cards/card_1782236231218.jpeg",
  },
  {
    id: "card_1782500000000",
    name: "北東軍第65歩兵大隊",
    type: "ユニット",
    world: "ユニフォール",
    attack: 2,
    defense: 3,
    description:
      "[貫通①][警戒]\n[歩兵]タグのユニットに対し与ダメージ時：自１を得る\n隣接するユニットのうち2つが[アトラス北東軍]のタグのユニットの時：ATK+１の修正を得る、HP+１の修正を得る",
    tags: ["アトラス北東軍", "純人間", "獣", "龍", "歩兵"],
    costs: {
      play: { human: 3, gold: 1, nature: 1, mineral: 0, fuel: 0, electric: 0, magic: 0 },
      act: { nature: 1, fuel: 1, human: 0, gold: 0, mineral: 0, electric: 0, magic: 0 },
      choice: [],
      choiceAct: [],
    },
    generates: { gold: 0, human: 0, nature: 0, mineral: 0, fuel: 0, electric: 0, magic: 0 },
    limit: 4,
    rarity: "通常",
  },
  {
    id: "card_1755701443493",
    name: "赫光の炉心",
    type: "ストラクト",
    world: "阿依の国のジャータカ",
    description: "魔⑤を支払いレストする：他の資源1種を5個得る",
    costs: {
      play: { magic: 7, human: 0, gold: 0, nature: 0, mineral: 0, fuel: 0, electric: 0 },
      act: {},
      choice: [],
      choiceAct: [],
    },
    generates: {},
    tags: [],
    rarity: "通常",
  },
  {
    id: "card_1782212242238",
    name: "【正体判明】怪獣(アイデンティティ・サッドガール)",
    type: "ユニット",
    world: "正体不明",
    attack: 8,
    defense: 8,
    description:
      "(このユニットの世界はニュートラルとしても扱う)\nこのユニットは｢【正体不明】骨の少女｣を裏に重ねた｢【正体不明】私｣を破壊しなければ出せない。\n出撃時：自分の墓地からコスト3以下のニュートラルユニットを2体まで場に出す。\n自分の全てのユニットは[不動][不攻]の影響を受けず、[装甲②][守護]を得る。",
    tags: ["海", "正体"],
    costs: { play: { magic: 1 }, act: {}, choice: [], choiceAct: [] },
    generates: {},
    limit: 4,
    rarity: "通常",
  },
  {
    id: "card_1782211899987",
    name: "【正体不明】(アンノウン) 私",
    type: "ユニット",
    world: "正体不明",
    attack: 1,
    defense: 1,
    description:
      "出撃時：自分のデッキの上から1枚を見る。\nそれがニュートラルのユニットカードならこのカードの裏に重ね、それ以外ならそのまま出来に戻す。\nこの時、正体不明のカードを重ねたなら、そのカードの効果を1つ選んで獲得する。それが出撃時効果なら即座に発動する。",
    tags: ["純人間"],
    costs: { play: { human: 1 }, act: {}, choice: [], choiceAct: [] },
    generates: {},
    limit: 4,
    rarity: "通常",
  },
  {
    id: "card_1782297782539",
    name: "【正体不明】虚空(アンノウン・ゴースト)",
    type: "ユニット",
    world: "正体不明",
    attack: 0,
    defense: 1,
    description:
      "(このユニットの世界はニュートラルとしても扱う)\n(※HPが0以下のユニットは破棄される)\n[不動][不攻]\n出撃時：自分のニュートラルユニット1体の効果を消す。",
    tags: [],
    costs: { play: {}, act: {}, choice: [], choiceAct: [] },
    generates: {},
    limit: 4,
    rarity: "通常",
  },
  {
    id: "card_1782208064951",
    name: "【正体不明】色彩(アンノウン・カラフル)",
    type: "ユニット",
    world: "正体不明",
    attack: 0,
    defense: 1,
    description:
      "(このユニットの世界はニュートラルとしても扱う)\n[不動][不攻]\n出撃時：自分の場のユニットの数だけ手札を捨てる。\nターン終了時：場のユニットを1体選んでもよい。指定されたユニットの、召喚に指定された資源の種類を自由に変更する。",
    tags: [],
    costs: { play: { magic: 3 }, act: {}, choice: [], choiceAct: [] },
    generates: {},
    limit: 4,
    rarity: "通常",
  },
  {
    id: "card_1782211496085",
    name: "【正体不明】保安官(アンノウン・シェリフ)",
    type: "ユニット",
    world: "正体不明",
    attack: 2,
    defense: 2,
    description:
      "(このユニットの世界はニュートラルとしても扱う)\n[不動][不攻][機動]\n出撃時：自身の2行目に相手のユニットがいるなら、それらを全て更新させ、自分のユニット1体の[不動][不攻]を消す。",
    tags: [],
    costs: { play: { magic: 2 }, act: {}, choice: [], choiceAct: [] },
    generates: {},
    limit: 4,
    rarity: "通常",
  },
  {
    id: "card_1782208333313",
    name: "正体隠匿(インポスター)",
    type: "タクト",
    world: "正体不明",
    description:
      "自分のニュートラルユニット1体を破壊する。\n相手か自分の墓地から、破壊したユニットと同じコスト総量のユニットを1体選び、自分のコントロールカードとして破壊したユニットのいた列に出す。",
    tags: [],
    costs: { play: { magic: 6 }, act: {}, choice: [], choiceAct: [] },
    generates: {},
    limit: 4,
    tactSubType: "通常",
    rarity: "通常",
  },
  {
    id: "card_1782561876492",
    name: "異界で見た同胞",
    type: "タクト",
    world: "ユニフォール",
    description:
      "フィールドの自分の[純人間]タグを持つユニットを2枚まで除外する\n\n世界《ユニフォール》の[勇者]タグを持つユニットを除外したなら\nそのユニットのステータスの合計を自身の[純人間]ユニットに補正する\n\n\n世界《ヘルメネアの大地》の[純人間]タグを持つユニットを除外したなら\nそのユニットのカウンターを自身の[勇者]ユニットに移す。",
    flavorText:
      "「もし君が唯一の人であるなら、僕らは同胞なのだろうね」\n\n「はっきりは言えないな、その物語は終わりを迎えつつある」\n\n「終わり…か」",
    tags: ["リ・サンティウ連合王国", "リッサジオール連合王国", "唯字論", "王国勇者主義", "通常"],
    costs: { play: { gold: 1, magic: 1 }, act: {}, choice: [], choiceAct: [] },
    generates: {},
    limit: 4,
    tactSubType: "通常",
    rarity: "通常",
    imageUrl: "assets/cards/card_1782561876492.jpeg",
  },
  {
    id: "card_1782560224044",
    name: "唯一無二にして大儀な。",
    type: "タクト",
    world: "ヘルメネアの大地",
    description:
      "デッキの上から1枚を墓地に送る\n\nこのカードが墓地にある時、このカードを除外し人1を支払い以下の効果を発動する\n・墓地から[唯字論]タグを持つカードを手札に加える\n・唯字論カウンターを任意のユニットに1載せる\n・任意の[純人間]ユニットから任意の回数だけ唯字論カウンターを取り除き、\n　その回数だけ０/＋１の補正を与える\n",
    flavorText: "唯一なる高貴な血を流し、唯一儀義を持つ儀式を",
    tags: ["唯字論", "通常"],
    costs: { play: { human: 2 }, act: {}, choice: [], choiceAct: [] },
    generates: {},
    limit: 4,
    tactSubType: "通常",
    rarity: "通常",
    imageUrl: "assets/cards/card_1782560224044.jpeg",
  },
  {
    id: "card_1782600607874",
    name: "北東軍第113騎兵大隊",
    type: "ユニット",
    world: "ユニフォール",
    attack: 3,
    defense: 6,
    description:
      "[機動]　[警戒]　[奇襲]　\n[歩兵]タグのユニットに対し撃破時：自①を得る\n攻撃時に人①自②を支払った場合：[貫通③]、[装甲①]、ATK+③の修正を得る\n隣接するユニットのうち２つが[アトラス北東軍]のタグのユニットの時：ATK+①、HP+①の修正を得る",
    flavorText:
      "騎兵の本領はその機動力と、それを活かした突撃能力の高さにある。\n彼らはいずれ装甲騎兵に取って代わられる。だが、それは今では無い。",
    tags: ["アトラス北東軍", "純人間", "獣", "龍", "騎兵"],
    costs: {
      play: { human: 3, gold: 2, nature: 2, mineral: 1, fuel: 0, electric: 0, magic: 0 },
      act: { gold: 1, nature: 2, human: 0, mineral: 0, fuel: 0, electric: 0, magic: 0 },
      choice: [],
      choiceAct: [],
    },
    generates: { gold: 0, human: 0, nature: 0, mineral: 0, fuel: 0, electric: 0, magic: 0 },
    limit: 4,
    rarity: "通常",
    imageUrl: "assets/cards/card_1782600607874.jpeg",
  },
];
