/** Deckmaker-exported cards not yet in deck_data.js (images omitted — resolved via assets/cards/{id}.png). */
export default [
  {
    id: "card_1782315551233",
    name: "第６サラマンダー混成支援大隊",
    type: "ユニット",
    world: "ユニフォール",
    attack: 1,
    defense: 3,
    description: "出撃時：２枚ドローする",
    flavorText: "サラマンダーはお手伝いが大好き！...機関銃も握れる！",
    tags: ["ルディワ公国", "歩兵", "戦車", "機械", "魔物", "車両"],
    costs: {
      play: { nature: 2, human: 2, fuel: 0, gold: 0, mineral: 0, electric: 0, magic: 0 },
      act: { nature: 1, human: 0, fuel: 0, gold: 0, mineral: 0, electric: 0, magic: 0 },
      choice: [],
      choiceAct: [],
    },
    generates: { mineral: 0, magic: 0, electric: 0, nature: 0, fuel: 0, gold: 0, human: 0 },
    limit: 4,
    roles: [],
    tactSubType: null,
    rarity: "通常",
    imageUrl: "assets/cards/card_1782315551233.jpeg",
  },
  {
    id: "card_1782307790847",
    name: "北東軍第33師団砲中隊",
    type: "ユニット",
    world: "ユニフォール",
    attack: 2,
    defense: 2,
    description: "[衝撃][曲射②]",
    flavorText: "「本格的な砲撃支援に比べたら貧相かもしれないが、\n衝撃と畏怖を叩き込むには必要不可欠だ。」",
    tags: ["アトラス北東軍", "純人間", "獣", "龍", "砲"],
    costs: {
      play: { human: 1, mineral: 2, fuel: 0, gold: 0, nature: 0, electric: 0, magic: 0 },
      act: { mineral: 2, human: 0, fuel: 0, gold: 0, nature: 0, electric: 0, magic: 0 },
      choice: [],
      choiceAct: [],
    },
    generates: { mineral: 0, magic: 0, electric: 0, nature: 0, fuel: 0, gold: 0, human: 0 },
    limit: 4,
    roles: [],
    tactSubType: null,
    rarity: "通常",
    imageUrl: "assets/cards/card_1782307790847.jpeg",
  },
  {
    id: "card_1782303856785",
    name: "第8装甲騎兵大隊",
    type: "ユニット",
    world: "ユニフォール",
    attack: 4,
    defense: 6,
    description: "[貫通①][装甲②][機動][警戒]",
    flavorText: "我ら、騎兵の誇り。第8、雪原より砂漠に至るまで、誰にも劣らぬ精鋭なり。",
    tags: ["グラダナ連邦共和国", "純人間", "獣", "龍", "歩兵", "車両"],
    costs: {
      play: { fuel: 2, gold: 1, human: 3, nature: 0, mineral: 0, electric: 0, magic: 0 },
      act: { fuel: 1, gold: 1, nature: 1, human: 0, mineral: 0, electric: 0, magic: 0 },
      choice: [],
      choiceAct: [],
    },
    generates: { nature: 0, magic: 0, electric: 0, mineral: 0, fuel: 0, human: 0, gold: 0 },
    limit: 4,
    roles: [],
    tactSubType: null,
    rarity: "通常",
    imageUrl: "assets/cards/card_1782303856785.jpeg",
  },
  {
    id: "card_1782287759412",
    name: "DTO前線指揮所",
    type: "コア",
    world: "ユニフォール",
    life: 20,
    defense: 20,
    handLimit: 7,
    drawPerTurn: 1,
    initialHand: 6,
    limit: 4,
    description:
      "[アトラス北東軍][グラダナ連邦共和国][ルディワ公国]タグのプレイコスト5以下のカードを20枚以上入れていない場合、このカードは使用できない。\n[アトラス北東軍][グラダナ連邦共和国][ルディワ公国]タグのユニット全員がATK+①の修正を得る",
    flavorText: "締約勢力は、共同の安全を回復および維持するため、\n必要と認める行動を直ちに実施する。",
    tags: ["グラダナ連邦共和国", "アトラス北東軍", "ルディワ公国"],
    initialResources: { mineral: 1, gold: 4, human: 2, nature: 0, fuel: 0, electric: 0, magic: 0 },
    defeatCondition: "このカードが破壊される。",
    costs: { play: {}, act: {}, choice: [], choiceAct: [] },
    generates: {},
    roles: [],
    tactSubType: null,
    rarity: "通常",
    imageUrl: "assets/cards/card_1782287759412.jpeg",
  },
  {
    id: "card_1782311181226",
    name: "壊滅怪異",
    type: "ユニット",
    world: "阿依の国のジャータカ",
    attack: 0,
    defense: 1,
    description: "[機動][自爆⑩]",
    flavorText: "「あと一度の攻勢で我々は勝利する」その言葉は三年前にも聞いた。",
    tags: ["機械", "ロボット", "怪異"],
    costs: {
      play: { magic: 1, mineral: 1, fuel: 0, gold: 0, nature: 0, human: 0, electric: 0 },
      act: { electric: 0, magic: 0, mineral: 0, nature: 0, fuel: 0, gold: 0, human: 0 },
      choice: [],
      choiceAct: [],
    },
    generates: { fuel: 0, human: 0, gold: 0, nature: 0, magic: 0, mineral: 0, electric: 0 },
    limit: 4,
    roles: [],
    tactSubType: null,
    rarity: "通常",
    imageUrl: "assets/cards/card_1782311181226.jpeg",
  },
  {
    id: "card_1782237267608",
    name: "北東軍第27迫撃砲分隊",
    type: "ユニット",
    world: "ユニフォール",
    attack: 1,
    defense: 1,
    description: "[衝撃][連撃①][曲射②]\n「歩兵」タグを持っているユニットに対し与攻撃時：ATK+①の修正を得る。",
    flavorText: "砲兵が戦場の女神だとしたら迫撃砲兵は戦場の天使なのだろうか？\n少なくとも、相手はそうは思っていないだろう。",
    tags: ["アトラス北東軍", "純人間", "獣", "龍", "歩兵", "砲"],
    costs: {
      play: { human: 1, mineral: 1, gold: 1, fuel: 0, nature: 0, electric: 0, magic: 0 },
      act: { nature: 1, human: 0, fuel: 0, gold: 0, mineral: 0, electric: 0, magic: 0 },
      choice: [],
      choiceAct: [],
    },
    generates: { mineral: 0, magic: 0, electric: 0, nature: 0, fuel: 0, gold: 0, human: 0 },
    limit: 4,
    roles: [],
    tactSubType: null,
    rarity: "通常",
    imageUrl: "assets/cards/card_1782237267608.jpeg",
  },
  {
    id: "card_1782308723608",
    name: "特別計画",
    type: "タクト",
    world: "ニュートラル",
    description: "コスト18以上のカードを2枚、手札に加える",
    flavorText: "「我々の計画は必ず世界を席巻させる。\nその為には諸君らの弛まぬ努力が＿」",
    tags: ["政策", "計画"],
    costs: {
      play: { gold: 1, human: 0, magic: 0, electric: 0, nature: 0, fuel: 0, mineral: 0 },
      act: {},
      choice: [],
      choiceAct: [],
    },
    generates: { gold: 0, mineral: 0, nature: 0, fuel: 0, electric: 0, magic: 0, human: 0 },
    limit: 4,
    roles: [],
    tactSubType: "通常",
    rarity: "通常",
    imageUrl: "assets/cards/card_1782308723608.jpeg",
  },
  {
    id: "card_1782225519182",
    name: "北東軍最高司令官",
    type: "ユニット",
    world: "ユニフォール",
    attack: 10,
    defense: 20,
    description:
      "[装甲⑩]　[貫通⑤]　[連撃①]　[神話]　[警戒]　[守護]　与ダメージ時：、鉱④を得る、自④を得る\n自②を支払う：HP⑤の修正を得る\n「北東軍総司令部」がコアカードの時：ATK+⑤の修正を得る\nフィールド上に「アトラス北東軍」タグのユニットが存在する時：対象ユニット全員がATK+③の修正を得る\nこのユニットは「アトラス北東軍」タグのユニットからのダメージを受けない。",
    flavorText:
      "「前線に赴くのは久々だな…この砲声と焦げ臭さも、将軍達の無謀な戦争計画を聞かされるよりはマシだな。」",
    tags: ["アトラス北東軍", "歩兵", "神話"],
    costs: {
      play: { human: 10, gold: 10, nature: 10, mineral: 10, fuel: 0, electric: 0, magic: 0 },
      act: { nature: 4, mineral: 4, gold: 0, human: 0, fuel: 0, electric: 0, magic: 0 },
      choice: [],
      choiceAct: [],
    },
    generates: { nature: 4, mineral: 4, gold: 0, human: 0, fuel: 0, electric: 0, magic: 0 },
    limit: 4,
    roles: [],
    tactSubType: null,
    rarity: "神話",
    imageUrl: "assets/cards/card_1782225519182.jpeg",
  },
  {
    id: "card_1782330659181",
    name: "ÜSPz.76V Aust. A",
    type: "ユニット",
    world: "ユニフォール",
    attack: 6,
    defense: 20,
    description:
      "[装甲⑧][貫通⑥][衝撃][機動][連撃①][曲射①]\n鉱6を支払う：ATK+④を得る",
    flavorText:
      "軍事費の無駄だと最高司令官に一蹴されたこの超重戦車は、技術将校達による数ヶ月にも及ぶ拷問とも思える“説得”によって製造許可が降りた。",
    tags: ["アトラス北東軍", "機械", "車両", "戦車"],
    costs: {
      play: { mineral: 15, fuel: 10, gold: 10, human: 2, nature: 0, electric: 0, magic: 0 },
      act: { gold: 5, fuel: 5, human: 0, nature: 0, mineral: 0, electric: 0, magic: 0 },
      choice: [],
      choiceAct: [],
    },
    generates: { gold: 0, mineral: 0, nature: 0, fuel: 0, electric: 0, magic: 0, human: 0 },
    limit: 4,
    roles: [],
    tactSubType: null,
    rarity: "通常",
    imageUrl: "assets/cards/card_1782330659181.jpeg",
  },
  {
    id: "card_1782361783127",
    name: "GNS Sovereign",
    type: "タクト",
    world: "ユニフォール",
    description: "すべての相手ユニットを破壊する",
    flavorText: "「自由なる海と、自由なる人民に、我らは奉仕する。」",
    tags: ["グラダナ連邦共和国", "命令"],
    costs: {
      play: { fuel: 8, gold: 8, mineral: 8, human: 8, electric: 0, magic: 0, nature: 0 },
      act: {},
      choice: [],
      choiceAct: [],
    },
    generates: { gold: 0, human: 0, nature: 0, mineral: 0, fuel: 0, electric: 0, magic: 0 },
    limit: 4,
    roles: [],
    tactSubType: "通常",
    rarity: "通常",
    imageUrl: "assets/cards/card_1782361783127.jpeg",
  },
  {
    id: "card_1782510000000",
    name: "第122戦車大隊",
    type: "ユニット",
    world: "ユニフォール",
    attack: 4,
    defense: 8,
    description: "[装甲④][貫通③][衝撃][機動][曲射①]",
    flavorText: "\"我ら鋼鉄の騎兵、連邦の槍と盾\"",
    tags: ["グラダナ連邦共和国", "機械", "車両", "戦車"],
    costs: {
      play: { gold: 4, human: 2, nature: 0, mineral: 3, fuel: 3, electric: 0, magic: 0 },
      act: { fuel: 3, mineral: 1, gold: 2, human: 0, nature: 0, electric: 0, magic: 0 },
      choice: [],
      choiceAct: [],
    },
    generates: { gold: 0, human: 0, nature: 0, mineral: 0, fuel: 0, electric: 0, magic: 0 },
    limit: 4,
    roles: [],
    tactSubType: null,
    rarity: "通常",
    imageUrl: "assets/cards/card_1782510000000.jpeg",
  },
  {
    id: "card_1755670973607",
    name: "王城ノーベルグ",
    type: "コア",
    world: "ヘルメネアの大地",
    defense: 20,
    description: "毎ターン：人②と金②を得る",
    initialResources: {
      human: 0,
      nature: 0,
      mineral: 0,
      gold: 8,
      electric: 0,
      fuel: 0,
      magic: 1,
    },
    generates: {
      human: 2,
      gold: 2,
      nature: 0,
      mineral: 0,
      fuel: 0,
      electric: 0,
      magic: 0,
    },
    tags: ["リ･サンティウ連合王国"],
    rarity: "通常",
  },
  {
    id: "card_1782225814944",
    name: "石油コンビナート",
    type: "ストラクト",
    world: "ユニフォール",
    description: "レストする(ストラクトカード)：燃⑤を得る",
    generates: {
      fuel: 5,
      electric: 0,
      human: 0,
      mineral: 0,
      nature: 0,
      magic: 0,
      gold: 0,
    },
    costs: {
      play: { human: 1, nature: 0, mineral: 1, electric: 0, fuel: 0, magic: 0, gold: 1 },
      act: {},
      choice: [],
      choiceAct: [],
    },
    tags: ["産業", "工場", "科学"],
    rarity: "通常",
  },
];
